### ISSUE TITLE
Support for Alexa 2nd - No devices Found

### ISSUE THREAD

**Issue by vslinuxdotnet** [simap/fauxmoesp#2]
Hello,
Seams that this new version don't find anything on searching devices in Android APP or using Alexa 2nd.
I enable the debug and see that the responses are there, but none is discovered in app.
In other libs that enable smart devices on ESP, there is a TCP port on any device, I see or lib code and don't figure it out where you define this unique device id.
This my be the cause.
You help will be appreciated
Thank you.

**Comment by simap** [comment]
This is just a clone I threw up on GH (mostly for myself, but seems that other folks find it useful), I updated it, maybe it works better now?

see the original https://bitbucket.org/xoseperez/fauxmoesp
