### ISSUE TITLE
Multiple libraries were found for "WiFi.h"

### ISSUE THREAD

**Issue by rahul2244** [simap/fauxmoesp#3]
Multiple libraries were found for "WiFi.h"
In file included from C:\Users\rp787\AppData\Local\Temp\arduino_modified_sketch_939332\fauxmoESP_Basic.ino:7:0:

 Used: C:\Users\rp787\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
C:\Users\rp787\Documents\Arduino\libraries\FauxmoESP\src/fauxmoESP.h:63:26: fatal error: AsyncTCP.h: No such file or directory

 Not used: C:\Program
compilation terminated.

Multiple libraries were found for "fauxmoESP.h"
 Used: C:\Users\rp787\Documents\Arduino\libraries\FauxmoESP
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by simap** [comment]
this is a clone of https://bitbucket.org/xoseperez/fauxmoesp
