### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by cgmckeever** [simap/fauxmoesp#4]
Hi! I know this is a fork from https://bitbucket.org/xoseperez/fauxmoesp/src/master/ .. but Im running into an issue, and just wondering if this still works. I had it all working a year ago, but with a fresh install of sketch, esp2866, fauxmo Alexa never recognizes it. 

Thought if you were still active, you may know - thanks

**Comment by simap** [comment]
Sorry, haven't used this in a while. I'd check with the upstream, I just had this for access through github.
