### ISSUE TITLE
Alexa is confusing when you have Philips Hue on same network

### ISSUE THREAD

**Issue by hectorbarranca** [simap/fauxmoesp#6]
Hi!

First of all it is a great project.

I detected 2 possible errors, the first one when you have a Philips Hue and you try to add the ESP8266 device to a room from the application, the application adds the Hue and not the ESP8266, I'm not sure but possibly adds the first registered device, possibly bacause of the ID. Outside of room operations, normal operation works excellent.

I put a photo to explain the steps to reproduce the error: [img](http://page.hectorhd.com/i.png)

The other problem is not so serious and comes only when the device is turned on for the first time, it seems to send the turn on instruction 2 times, maybe that because the maximum possible value is 254 and the first time it sends 255:
[MAIN] Device #2 (Clima Sala) state: ON value: 255
[MAIN] Device #2 (Clima Sala) state: ON value: 254

Thanks for your time to check the issue =)

**Comment by simap** [comment]
This is't the project repo, this is a clone
